<?php
use VConnect\Blog\Block\PostsList;

/**
 * @var $block PostsList
 * @var $posts \VConnect\Blog\Model\Post[]
 * @var $post \VConnect\Blog\Model\Post
 */

$posts = $block->getPosts();
?>

<?php if (count($posts) === 0): ?>
    <p>There are no posts in this blog.</p>
<?php else: ?>
        <?php foreach ($posts as $post): ?>
                <a href="<?= $block->getPostUrl($post); ?>">
                    <h3><?= $post->getTitle(); ?></h3>
                </a>
                <div class="vconnect-blog-post-list-publish-date">
                    <?= $post->getPublishDate(); ?>
                </div>
                <div class="vconnect-blog-post-list-announce">
                    <?= $post->getAnnounce(); ?>
                </div>
        <?php endforeach; ?>
<?php endif; ?>
